root:
  host: https://www.pivotaltracker.com
  root_path: /services/v5/
  authorization_type: bearer
  default_role: admin
  headers:
    accept: application/json
    Content-Type: application/json
  roles:
    admin:
      username: admin
      password: admin
      headers:
        X-TrackerToken: e0b6db9c0cc59332f65349b85a6a3b26